### PR TITLE
Remove trailing whitespaces

### PR DESCRIPTION
**Pull request by jaemolihm**
Removed trailing whitespaces in `mmn2uHu.py`.

To see the codecov checks are working.

### CODE REVIEW

**Comment by jaemolihm** [comment]
The checks are not working... I have no idea why.
Checks works well for my fork https://github.com/jaemolihm/wannier-berri/pull/3.

**Review by stepan-tsirkin — APPROVED** [review]
All greatr

**Comment by stepan-tsirkin** [comment]
Hi @jaemolihm 

Yes, I do not understand this either. Actually Codecov made a report, and commented  as @codecov-commenter  (see above) Just the status "has not been reported". 

What does it actually meant to "pass a codecov check"?

**Comment by jaemolihm** [comment]
The codecov checks 1) whether the added codes are covered by tests, and 2) whether the total coverage has increased or not.

With an additional push (another trailing whitespace deleted in `vaspspn.py`), the check now reports. (I still do not understand why.)

You can make the codecov checks not required if you want.
https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule (see point 7)

**Comment by jaemolihm** [comment]
As this PR was made to test codecov checks, and as it seems working now, I will close it.

**Pull request closed without merging**
