### PR TITLE
Automatically add tag when running uploadpypi.sh

### PR DESCRIPTION
**Pull request by jaemolihm**

### CODE REVIEW

**Comment by stepan-tsirkin** [comment]
@jaemolihm , where should we generally write release notes? can it also be automatized?

**Comment by jaemolihm** [comment]
One option is to maintain a resease-notes.md file. We add things in the section e.g. "New in development version", and rename it into "New in vx.y.z" whe doing a release. But this is not automatic.
Similar thing in QE: https://gitlab.com/QEF/q-e/-/blob/develop/Doc/release-notes

In GitHub, in create new release, there is automatically generate release note, which lists the title of the issues and merged PRs.
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

For example:
## What's Changed
* Static Spin Hall conductivity in FermiOcean by @jaemolihm in https://github.com/wannier-berri/wannier-berri/pull/85
* fixed a bug with specific_parameters for user quantities by @stepan-tsirkin in https://github.com/wannier-berri/wannier-berri/pull/88
* fixes in models, tabulating morb and der_morb by @stepan-tsirkin in https://github.com/wannier-berri/wannier-berri/pull/86


**Full Changelog**: https://github.com/wannier-berri/wannier-berri/compare/v0.10.0...v0.10.1

**Comment by stepan-tsirkin** [comment]
@jaemolihm  , for the second option we still need to make releases on github, which we decided not to do

So, let's try to maintain a file where we will write things manually.

**Review by stepan-tsirkin — APPROVED** [review]

**Comment by jaemolihm** [comment]
> @jaemolihm , for the second option we still need to make releases on github, which we decided not to do
> 
> So, let's try to maintain a file where we will write things manually.

I mean, you can copy the contents there without making an actual GitHub release.

I agree we maintain a manual release note. If, in the future, that turn out to be too hard, we can discuss alternatives later.

**Pull request merged**
