### PR TITLE
smoothwers in calculators

### PR DESCRIPTION
**Pull request by stepan-tsirkin**
+ Allowed to set smoothers for `StaticCalculator`
+ moved smoothers to a separate file
+ discovered that in out tests the Ef step is so bigger than the smearing width, that smoother does not do anything. Increased smearing for Chiral tests (and changed corresponding reference files)

TODO (in future PRs)
+ allow smoothers for `DynamicCalculator`
+ increase smearing for other tests (where txt files are saved) ?

### CODE REVIEW

**Review by Liu-Xiaoxiong — COMMENTED** [review]
Looks good

**Comment by stepan-tsirkin** [comment]
@Liu-Xiaoxiong  "looks good" is not an "approving review"

**Comment by Liu-Xiaoxiong** [comment]
> @Liu-Xiaoxiong "looks good" is not an "approving review"

Emmmmmm,  'That was impressive, you have a real talent to make the incredible improvement!'

**Comment by stepan-tsirkin** [comment]
@Liu-Xiaoxiong , next time  go to "Files changed", press "review changes", select "approve" and admire my talent there

**Pull request merged**
