### PR TITLE
 fixed a bug with low-dimensional TB models

### PR DESCRIPTION
**Pull request by stepan-tsirkin**
Fix of a problem reported by Se Young Park on the mailing list.

### CODE REVIEW

**Review by jaemolihm — COMMENTED** [review]
Looks good, except one question. If `periodic` is not provided at all, it becomes `[True, True, True` (due to the `default_parameters`). Doesn't this behavior contradict "If less then 3 values provided, the rest are treated as ``False``"?

An option would be to force the argument `periodic` to be always of length 3.

**Comment by stepan-tsirkin** [comment]
I think there is no contradiction. If the argument `periodic` is not provided at all, it is taken as default `[True,True,True]`, i.e. as 3 values provided. If one provides `periodic=[]`, it is taken as `[False,False,False]`. Although, not sure if using wannierberri for non-periodic systems ever makes sense.

**Comment by stepan-tsirkin** [comment]
I mean "zero values provided" and "no values provided" are different things. Do you agree? Or is it confusing and needs more explanatory docstring?

**Comment by jaemolihm** [comment]
I see. Maybe adding "If not provided, set to ``(True, True, True)``." or something similar would remove the confusion.

**Comment by stepan-tsirkin** [comment]
Ok, I added the printing of default parameters to the docstrings. Now should be clear. 
I also set the frozen_max to -Inf , because  is nothing is known about frozen window, it should not be used for the orbital moment

**Review by jaemolihm — APPROVED** [review]

**Pull request merged**
